name: Daily Commit

on:
  schedule:
    # Runs every day at 10:30 UTC — you can change this time but keep it specific
    - cron: "30 10 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Make a small change
      - name: Add daily commit marker by 24f2005894@ds.study.iitm.ac.in
        run: |
          echo "Last run on $(date -u)" > last_run.txt
          git config user.name "GitHub Action Bot"
          git config user.email "24f2005894@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Daily commit on $(date -u)" || echo "No changes to commit"
          git push
